CREATE TABLE DISTRITO (
    COD_DIS CHAR(5) PRIMARY KEY,
    NOM_DIS VARCHAR(50)
);

CREATE TABLE PRODUCTO (
    COD_PRO CHAR(5) PRIMARY KEY,
    DES_PRO VARCHAR(50),
    PRE_PRO NUMERIC(10,2),
    SAC_PRO INTEGER,
    SMI_PRO INTEGER,
    UNI_PRO VARCHAR(20),
    LIN_PRO VARCHAR(30),
    IMP_PRO VARCHAR(10)
);

CREATE TABLE CLIENTE (
    COD_CLI CHAR(5) PRIMARY KEY,
    RSO_CLI VARCHAR(50),
    DIR_CLI VARCHAR(100),
    TLF_CLI CHAR(9),
    RUC_CLI CHAR(11),
    COD_DIS CHAR(5),
    FEC_REG DATE,
    TIP_CLI VARCHAR(10),
    CON_CLI VARCHAR(50),
    FOREIGN KEY (COD_DIS) REFERENCES DISTRITO(COD_DIS)
);

CREATE TABLE VENDEDOR (
    COD_VEN CHAR(5) PRIMARY KEY,
    NOM_VEN VARCHAR(20),
    APE_VEN VARCHAR(20),
    SUE_VEN NUMERIC(10,2),
    FIN_VEN DATE,
    TIP_VEN VARCHAR(10),
    COD_DIS CHAR(5),
    FOREIGN KEY (COD_DIS) REFERENCES DISTRITO(COD_DIS)
);

CREATE TABLE PROVEEDOR (
    COD_PRV CHAR(5) PRIMARY KEY,
    RSO_PRV VARCHAR(80),
    DIR_PRV VARCHAR(100),
    TLF_PRV CHAR(15),
    COD_DIS CHAR(5),
    REP_PRV VARCHAR(80),
    FOREIGN KEY (COD_DIS) REFERENCES DISTRITO(COD_DIS)
);

CREATE TABLE FACTURA (
    NUM_FAC VARCHAR(12) PRIMARY KEY,
    FEC_FAC DATE,
    COD_CLI CHAR(5),
    FEC_CAN DATE,
    EST_FAC VARCHAR(10),
    COD_VEN CHAR(5),
    POR_IGV NUMERIC(5,2),
    FOREIGN KEY (COD_CLI) REFERENCES CLIENTE(COD_CLI),
    FOREIGN KEY (COD_VEN) REFERENCES VENDEDOR(COD_VEN)
);

CREATE TABLE DETALLE_FACTURA (
    NUM_FAC VARCHAR(12),
    COD_PRO CHAR(5),
    CAN_VEN INTEGER,
    PRE_VEN NUMERIC(10,2),
    PRIMARY KEY (NUM_FAC, COD_PRO),
    FOREIGN KEY (NUM_FAC) REFERENCES FACTURA(NUM_FAC),
    FOREIGN KEY (COD_PRO) REFERENCES PRODUCTO(COD_PRO)
);

CREATE TABLE ORDEN_COMPRA (
    NUM_OCO CHAR(5) PRIMARY KEY,
    FEC_OCO DATE,
    COD_PRV CHAR(5),
    FAT_OCO DATE,
    EST_OCO CHAR(1),
    FOREIGN KEY (COD_PRV) REFERENCES PROVEEDOR(COD_PRV)
);

CREATE TABLE DETALLE_COMPRA (
    NUM_OCO CHAR(5),
    COD_PRO CHAR(5),
    CAN_DET INTEGER,
    PRIMARY KEY (NUM_OCO, COD_PRO),
    FOREIGN KEY (NUM_OCO) REFERENCES ORDEN_COMPRA(NUM_OCO),
    FOREIGN KEY (COD_PRO) REFERENCES PRODUCTO(COD_PRO)
);

CREATE TABLE ABASTECIMIENTO (
    COD_PRV CHAR(5),
    COD_PRO CHAR(5),
    PRE_ABA NUMERIC(10,2),
    PRIMARY KEY (COD_PRV, COD_PRO),
    FOREIGN KEY (COD_PRV) REFERENCES PROVEEDOR(COD_PRV),
    FOREIGN KEY (COD_PRO) REFERENCES PRODUCTO(COD_PRO)
);
